require "html/pipeline"
require "html/pipeline/abbr/version"
require "html/pipeline/abbr/replace"
require "html/pipeline/abbr_filter.rb"
require "html/pipeline/auto_abbr_filter.rb"
require "html/pipeline/abbr_emoji_filter.rb"
